databases:
  - name: hospital-db
    databaseName: hospital_management
    user: hospital_admin
    plan: free

services:
  - type: web
    name: hospital-management
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
    autoDeploy: true
